//! Exact plain Möbius renderer for autonomous one-base FSC terminals.
//!
//! The embedded certificate is a typed, reproducible table generated by the
//! exhaustive ignored test at the bottom of this module.

use crate::{
    expr::Expr,
    factorized_section::{OneBaseDescriptor, compile_declared_one_base_descriptor},
};

// Generated offline with:
//
// cargo test -p rumba-core --release --features parse \
//   certificate_matches_exhaustive_generator -- --ignored --nocapture
//
// The generator below exhaustively enumerates every canonical production
// expression of AST cost <= 3 over constants 0..63, x/y, NOT, Scale, AND, OR,
// XOR, Add, and Mul. It evaluates the full 64x64 input table modulo 64, retains
// exactly the functions representable by (c0,c1,c2,c12), and records their
// minimum cost. Enumerating costs below four proves whether a candidate of cost
// <= 4 has a cheaper equivalent; enumeration never runs in production.
//
// Entries are sorted packed u32 values. The tuple key is
// c0 | (c1 << 6) | (c2 << 12) | (c12 << 18), and an entry is encoded as
// (key << 2) | minimum_cost. The expected output is 568 entries.
const CERTIFICATE_TABLE: [u32; 568] = [
    1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93,
    97, 101, 105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153, 157, 161, 165, 169,
    173, 177, 181, 185, 189, 193, 197, 201, 205, 209, 213, 217, 221, 225, 229, 233, 237, 241, 245,
    249, 253, 257, 263, 267, 271, 275, 279, 283, 287, 291, 295, 299, 303, 307, 311, 315, 319, 323,
    327, 331, 335, 339, 343, 347, 351, 355, 359, 363, 367, 371, 375, 379, 383, 387, 391, 395, 399,
    403, 407, 411, 415, 419, 423, 427, 431, 435, 439, 443, 447, 451, 455, 459, 463, 467, 471, 475,
    479, 483, 487, 491, 495, 499, 503, 507, 511, 514, 523, 767, 770, 783, 1023, 1026, 1043, 1279,
    1282, 1303, 1535, 1538, 1563, 1791, 1794, 1823, 2047, 2050, 2083, 2303, 2306, 2343, 2559, 2562,
    2603, 2815, 2818, 2863, 3071, 3074, 3123, 3327, 3330, 3383, 3583, 3586, 3643, 3839, 3842, 3903,
    4095, 4098, 4163, 4351, 4354, 4423, 4607, 4610, 4683, 4863, 4866, 4943, 5119, 5122, 5203, 5375,
    5378, 5463, 5631, 5634, 5723, 5887, 5890, 5983, 6143, 6146, 6243, 6399, 6402, 6503, 6655, 6658,
    6763, 6911, 6914, 7023, 7167, 7170, 7283, 7423, 7426, 7543, 7679, 7682, 7803, 7935, 7938, 8063,
    8191, 8194, 8323, 8447, 8450, 8583, 8703, 8706, 8843, 8959, 8962, 9103, 9215, 9218, 9363, 9471,
    9474, 9623, 9727, 9730, 9883, 9983, 9986, 10143, 10239, 10242, 10403, 10495, 10498, 10663,
    10751, 10754, 10923, 11007, 11010, 11183, 11263, 11266, 11443, 11519, 11522, 11703, 11775,
    11778, 11963, 12031, 12034, 12223, 12287, 12290, 12483, 12543, 12546, 12743, 12799, 12802,
    13003, 13055, 13058, 13263, 13311, 13314, 13523, 13567, 13570, 13783, 13823, 13826, 14043,
    14079, 14082, 14303, 14335, 14338, 14563, 14591, 14594, 14823, 14847, 14850, 15083, 15103,
    15106, 15343, 15359, 15362, 15603, 15615, 15618, 15863, 15871, 15874, 16123, 16127, 16130,
    16255, 16382, 16385, 16391, 16395, 16399, 16403, 16407, 16411, 16415, 16419, 16423, 16427,
    16431, 16435, 16439, 16443, 16447, 16451, 16455, 16459, 16463, 16467, 16471, 16475, 16479,
    16483, 16487, 16491, 16495, 16499, 16503, 16507, 16511, 16515, 16519, 16523, 16527, 16531,
    16535, 16539, 16543, 16547, 16551, 16555, 16559, 16563, 16567, 16571, 16575, 16579, 16583,
    16587, 16591, 16595, 16599, 16603, 16607, 16611, 16615, 16619, 16623, 16627, 16631, 16635,
    16639, 16643, 32770, 32779, 33023, 49154, 49167, 49407, 65538, 65555, 65791, 81922, 81943,
    82175, 98306, 98331, 98559, 114690, 114719, 114943, 131074, 131107, 131327, 147458, 147495,
    147711, 163842, 163883, 164095, 180226, 180271, 180479, 196610, 196659, 196863, 212994, 213047,
    213247, 229378, 229435, 229631, 245762, 245823, 246015, 262146, 262211, 262399, 278530, 278599,
    278783, 294914, 294987, 295167, 311298, 311375, 311551, 327682, 327763, 327935, 344066, 344151,
    344319, 360450, 360539, 360703, 376834, 376927, 377087, 393218, 393315, 393471, 409602, 409703,
    409855, 425986, 426091, 426239, 442370, 442479, 442623, 458754, 458867, 459007, 475138, 475255,
    475391, 491522, 491643, 491775, 507906, 508031, 508159, 524290, 524419, 524543, 540674, 540807,
    540927, 557058, 557195, 557311, 573442, 573583, 573695, 589826, 589971, 590079, 606210, 606359,
    606463, 622594, 622747, 622847, 638978, 639135, 639231, 655362, 655523, 655615, 671746, 671911,
    671999, 688130, 688299, 688383, 704514, 704687, 704767, 720898, 721075, 721151, 737282, 737463,
    737535, 753666, 753851, 753919, 770050, 770239, 770303, 786434, 786627, 786687, 802818, 803015,
    803071, 819202, 819403, 819455, 835586, 835791, 835839, 851970, 852179, 852223, 868354, 868567,
    868607, 884738, 884955, 884991, 901122, 901343, 901375, 917506, 917731, 917759, 933890, 934119,
    934143, 950274, 950507, 950527, 966658, 966895, 966911, 983042, 983283, 983295, 999426, 999671,
    999679, 1015810, 1016059, 1016063, 1032194, 1032319, 1032446, 1048579, 65028355, 66076931,
];

fn scaled(coefficient: i128, expression: Expr) -> Expr {
    Expr::scale(coefficient as u64, expression)
}

pub(crate) fn render_plain(descriptor: OneBaseDescriptor) -> Option<Expr> {
    let [c1, c2, xy_value] = descriptor.epsilon_nonzero;
    let c12 = xy_value.checked_sub(c1)?.checked_sub(c2)?;
    let [x, y] = descriptor.variables.map(Expr::Var);
    let mut terms = Vec::with_capacity(4);
    if descriptor.r0 != 0 {
        terms.push(Expr::Const(descriptor.r0 as u64));
    }
    if c1 != 0 {
        terms.push(scaled(c1, x.clone()));
    }
    if c2 != 0 {
        terms.push(scaled(c2, y.clone()));
    }
    if c12 != 0 {
        terms.push(scaled(c12, Expr::And(vec![x, y])));
    }
    Some(match terms.len() {
        0 => Expr::Const(0),
        1 => terms.pop()?,
        _ => Expr::Add(terms),
    })
}

fn same_descriptor(left: OneBaseDescriptor, right: OneBaseDescriptor) -> bool {
    left.variables == right.variables
        && left.r0 == right.r0
        && left.epsilon_nonzero == right.epsilon_nonzero
}

fn tuple_key(descriptor: OneBaseDescriptor) -> Option<u32> {
    let [c1, c2, xy_value] = descriptor.epsilon_nonzero;
    let coefficients = [
        descriptor.r0,
        c1,
        c2,
        xy_value.checked_sub(c1)?.checked_sub(c2)?,
    ];
    Some(
        coefficients
            .into_iter()
            .enumerate()
            .fold(0u32, |key, (index, value)| {
                key | (((value as u64 & 63) as u32) << (index * 6))
            }),
    )
}

fn minimum_cost(key: u32) -> Option<u8> {
    let index = CERTIFICATE_TABLE
        .binary_search_by_key(&key, |packed| packed >> 2)
        .ok()?;
    Some((CERTIFICATE_TABLE[index] & 3) as u8)
}

fn minimality_certified(descriptor: OneBaseDescriptor, cost: usize) -> bool {
    if !(1..=4).contains(&cost) {
        return false;
    }
    tuple_key(descriptor)
        .and_then(minimum_cost)
        .is_none_or(|minimum| usize::from(minimum) >= cost)
}

pub(crate) fn render_terminal(descriptor: OneBaseDescriptor) -> Option<Expr> {
    let candidate = render_plain(descriptor)?;
    let compiled = compile_declared_one_base_descriptor(&candidate, descriptor.variables)?;
    (same_descriptor(compiled, descriptor) && minimality_certified(descriptor, candidate.size()))
        .then_some(candidate)
}

#[cfg(test)]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};

    use super::*;
    use crate::expr::VarId;
    #[cfg(feature = "parse")]
    use crate::parser::parse_expr;

    const VARIABLES: [VarId; 2] = [VarId(0), VarId(1)];

    #[cfg(feature = "parse")]
    fn descriptor(source: &str) -> OneBaseDescriptor {
        compile_declared_one_base_descriptor(
            &parse_expr(source).expect("test expression"),
            VARIABLES,
        )
        .expect("one-base descriptor")
    }

    #[test]
    #[cfg(feature = "parse")]
    fn plain_candidates_recompile_exactly() {
        for source in [
            "7 + 3*v0 - 5*v1",
            "9 + 4*v0 + 6*v1 + 8*(v0&v1)",
            "9223372036854775807*v0 - 9*v1",
        ] {
            let source = descriptor(source);
            let candidate = render_plain(source).expect("plain candidate");
            let compiled = compile_declared_one_base_descriptor(&candidate, VARIABLES)
                .expect("candidate descriptor");
            assert!(same_descriptor(compiled, source));
        }
    }

    #[test]
    #[cfg(feature = "parse")]
    fn minimality_gate_accepts_cost_four_and_rejects_cost_five() {
        let descriptor = descriptor("1 + 2*v0");
        let candidate = render_terminal(descriptor).expect("cost-four terminal");
        assert_eq!(candidate.size(), 4);
        assert!(!minimality_certified(descriptor, 5));
    }

    #[test]
    fn certificate_is_well_formed() {
        assert_eq!(CERTIFICATE_TABLE.len(), 568);
        assert!(
            CERTIFICATE_TABLE
                .iter()
                .all(|packed| matches!(packed & 3, 1..=3))
        );
        assert!(
            CERTIFICATE_TABLE
                .windows(2)
                .all(|pair| pair[0] >> 2 < pair[1] >> 2)
        );
    }

    fn insert_cost(expression: Expr, costs: &mut [BTreeSet<Expr>; 4]) {
        let expression = match expression {
            Expr::Const(value) => Expr::Const(value & 63),
            expression => expression,
        };
        let cost = expression.size();
        if cost <= 3 {
            costs[cost].insert(expression);
        }
    }

    fn eval_mod64(expression: &Expr, variables: [u8; 2]) -> u8 {
        match expression {
            Expr::Var(variable) => variables[variable.0] & 63,
            Expr::Const(value) => (value & 63) as u8,
            Expr::Not(child) => !eval_mod64(child, variables) & 63,
            Expr::Scale(coefficient, child) => {
                ((coefficient & 63) as u8).wrapping_mul(eval_mod64(child, variables)) & 63
            }
            Expr::And(children) => children
                .iter()
                .map(|child| eval_mod64(child, variables))
                .fold(63, |left, right| left & right),
            Expr::Or(children) => children
                .iter()
                .map(|child| eval_mod64(child, variables))
                .fold(0, |left, right| left | right),
            Expr::Xor(children) => children
                .iter()
                .map(|child| eval_mod64(child, variables))
                .fold(0, |left, right| left ^ right),
            Expr::Add(children) => {
                children
                    .iter()
                    .map(|child| eval_mod64(child, variables))
                    .fold(0u8, u8::wrapping_add)
                    & 63
            }
            Expr::Mul(children) => {
                children
                    .iter()
                    .map(|child| eval_mod64(child, variables))
                    .fold(1u8, u8::wrapping_mul)
                    & 63
            }
        }
    }

    fn reduced_onebase_key(expression: &Expr) -> Option<u32> {
        let c0 = eval_mod64(expression, [0, 0]);
        let c1 = eval_mod64(expression, [1, 0]).wrapping_sub(c0) & 63;
        let c2 = eval_mod64(expression, [0, 1]).wrapping_sub(c0) & 63;
        let c12 = eval_mod64(expression, [1, 1])
            .wrapping_sub(c0)
            .wrapping_sub(c1)
            .wrapping_sub(c2)
            & 63;
        for x in 0..64u8 {
            for y in 0..64u8 {
                let expected = c0
                    .wrapping_add(c1.wrapping_mul(x))
                    .wrapping_add(c2.wrapping_mul(y))
                    .wrapping_add(c12.wrapping_mul(x & y))
                    & 63;
                if eval_mod64(expression, [x, y]) != expected {
                    return None;
                }
            }
        }
        Some(u32::from(c0) | (u32::from(c1) << 6) | (u32::from(c2) << 12) | (u32::from(c12) << 18))
    }

    fn generated_certificate() -> Vec<u32> {
        // Exhaustive production grammar at AST cost < 4:
        // constants, x/y, NOT, Scale, AND, OR, XOR, Add, and Mul.
        let mut costs: [BTreeSet<Expr>; 4] = std::array::from_fn(|_| BTreeSet::new());
        for constant in 0..64u64 {
            insert_cost(Expr::Const(constant), &mut costs);
        }
        insert_cost(Expr::Var(VARIABLES[0]), &mut costs);
        insert_cost(Expr::Var(VARIABLES[1]), &mut costs);

        let leaves = costs[1].iter().cloned().collect::<Vec<_>>();
        for child in &leaves {
            insert_cost(Expr::Not(Box::new(child.clone())), &mut costs);
            for coefficient in 0..64u64 {
                insert_cost(Expr::scale(coefficient, child.clone()), &mut costs);
            }
        }
        let unary_children = costs[2].iter().cloned().collect::<Vec<_>>();
        for child in &unary_children {
            insert_cost(Expr::Not(Box::new(child.clone())), &mut costs);
            for coefficient in 0..64u64 {
                insert_cost(Expr::scale(coefficient, child.clone()), &mut costs);
            }
        }
        for (left_index, left) in leaves.iter().enumerate() {
            for right in leaves.iter().skip(left_index) {
                for expression in [
                    Expr::And(vec![left.clone(), right.clone()]),
                    Expr::Or(vec![left.clone(), right.clone()]),
                    Expr::Xor(vec![left.clone(), right.clone()]),
                    Expr::Add(vec![left.clone(), right.clone()]),
                    Expr::product(vec![left.clone(), right.clone()]),
                ] {
                    insert_cost(expression, &mut costs);
                }
            }
        }

        let mut minimum = BTreeMap::<u32, u8>::new();
        for (cost, expressions) in costs.iter().enumerate().skip(1) {
            for expression in expressions {
                let Some(key) = reduced_onebase_key(expression) else {
                    continue;
                };
                minimum
                    .entry(key)
                    .and_modify(|current| *current = (*current).min(cost as u8))
                    .or_insert(cost as u8);
            }
        }
        minimum
            .into_iter()
            .map(|(key, cost)| (key << 2) | u32::from(cost))
            .collect()
    }

    #[test]
    #[ignore = "exhaustively regenerates the modulo-64 AST<4 certificate"]
    fn certificate_matches_exhaustive_generator() {
        let certificate = generated_certificate();
        assert_eq!(certificate.as_slice(), CERTIFICATE_TABLE.as_slice());
        assert_eq!(certificate.len(), 568);
    }
}
