WHITESPACE = _{ " " | "\t" | "\n" }

expr = { or }

or  = { xor ~ ("|" ~ xor)* }
xor = { and ~ ("^" ~ and)* }
and = { comp ~ ("&" ~ comp)* }

comp    = { add ~ (comp_op ~ add)* }
comp_op = { "<=" | "<" | ">=" | ">" | "==" | "!=" }

add    = { mul ~ (add_op ~ mul)* }
add_op = { "+" | "-" }

mul = { shift ~ ("*" ~ shift)* }

shift    = { unary ~ (shift_op ~ unary)* }
shift_op = { "<<" | ">>" }

unary    = { unary_op ~ unary | atom }
unary_op = { "!" | "~" | "-" }

atom = { number | var | "(" ~ expr ~ ")" }

number = { hex_number | dec_number }

dec_number = @{ ASCII_DIGIT+ }
hex_number = @{ "0x" ~ ASCII_HEX_DIGIT+ }

var = @{ "v" ~ ASCII_DIGIT+ }
