#ifndef RUMBA_H
#define RUMBA_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define RUMBA_EXPR_REPR_FLAG_LATEX 1

#define RUMBA_EXPR_REPR_FLAG_HEX 2

/**
 * The type of an expression
 */
typedef enum RUMBA_EXPR_TYPE {
  /**
   * A variable
   */
  RUMBA_EXPR_TYPE_VAR,
  /**
   * A constant
   */
  RUMBA_EXPR_TYPE_CONST,
  /**
   * A bitwise not
   */
  RUMBA_EXPR_TYPE_NOT,
  /**
   * A multiplication between a constant and an expression
   */
  RUMBA_EXPR_TYPE_SCALE,
  /**
   * A bitwise and
   */
  RUMBA_EXPR_TYPE_AND,
  /**
   * A bitwise or
   */
  RUMBA_EXPR_TYPE_OR,
  /**
   * A bitwise xor
   */
  RUMBA_EXPR_TYPE_XOR,
  /**
   * A sum
   */
  RUMBA_EXPR_TYPE_ADD,
  /**
   * A product
   */
  RUMBA_EXPR_TYPE_MUL,
} RUMBA_EXPR_TYPE;

/**
 * The kind of an instruction
 */
typedef enum InsnKind {
  INSN_KIND_ASSIGN,
  INSN_KIND_UNKNOWN,
} InsnKind;

/**
 * Frees the expression `ptr`
 *
 * # Safety
 * Caller promises ptr is valid and from POOL
 */
void rumba_expr_free(void *ptr);

/**
 * Performs arithmentic reductions on `ptr` modulo 2^`n`
 * This function takes frees `ptr` and returns a new pointer
 */
void *rumba_expr_reduce(void *ptr, uint8_t n);

/**
 * Simplifies the MBA in `ptr` modulo 2^`n`
 * This function takes frees `ptr` and returns a new pointer
 */
void *rumba_expr_simplify(void *ptr, uint8_t n);

/**
 * Evaluates the epxression `ptr` modulo 2^`n`
 * on the variables in the array `arr` of length `len`
 */
uint64_t rumba_expr_eval(const void *ptr, uint8_t n, const uint64_t *arr, uintptr_t len);

/**
 * Counts the number of nodes in the expression `ptr`
 */
uintptr_t rumba_expr_size(const void *ptr);

/**
 * Returns a string representation of `ptr` modulo 2^`n`
 * `len` is the length of the returned string
 * `flags` RUMBA_EXPR_REPR_FLAG
 */
char *rumba_expr_repr(const void *ptr, uint8_t n, uintptr_t *len, uint8_t flags);

/**
 * Gets the type of the expression `ptr`.
 */
enum RUMBA_EXPR_TYPE rumba_expr_ty(const void *ptr);

/**
 * Gets the number of children of this node.
 * This should only be called on expressions of types
 * `And, Or, Xor, Mul, Add, Scale, Not`.
 */
uintptr_t rumba_expr_children_size(const void *ptr);

/**
 * Gets the `idx`-th child of this node.
 * This should only be called on expressions of types
 * `And, Or, Xor, Mul, Add, Scale, Not`.
 * `idx` should be less than `rumba_expr_children_size`.
 */
const void *rumba_expr_get_child(const void *ptr, uintptr_t idx);

/**
 * Mutably gets the `idx`-th child of this node.
 * This should only be called on expressions of types
 * `And, Or, Xor, Mul, Add, Scale, Not`.
 * `idx` should be less than `rumba_expr_children_size`.
 */
void *rumba_expr_get_child_mut(void *ptr, uintptr_t idx);

/**
 * Gets the constant of this node.
 * This should only be called on expressions of type `Const`.
 */
uint64_t rumba_expr_get_const(const void *ptr);

/**
 * Gets the variable id of this node.
 * This should only be called on expressions of type `Var`.
 */
uintptr_t rumba_expr_get_var(const void *ptr);

/**
 * Create a new CONSTANT expression
 */
void *rumba_make_const(uint64_t c);

/**
 * Create a new VARIABLE expression
 */
void *rumba_make_var(uintptr_t id);

/**
 * Create a new NOT expression.
 * `ptr` is freed and a new expression in allocated
 */
void *rumba_expr_bnot(void *ptr);

/**
 * Create a new AND expression.
 * `lhs` and `rhs` are freed and a new expression in allocated
 */
void *rumba_expr_band(void *lhs, void *rhs);

/**
 * Create a new XOR expression.
 * `lhs` and `rhs` are freed and a new expression in allocated
 */
void *rumba_expr_bxor(void *lhs, void *rhs);

/**
 * Create a new OR expression.
 * `lhs` and `rhs` are freed and a new expression in allocated
 */
void *rumba_expr_bor(void *lhs, void *rhs);

/**
 * Create a new ADD expression.
 * `ptr` is freed and a new expression in allocated
 */
void *rumba_expr_add(void *lhs, void *rhs);

/**
 * Create a new MUL expression.
 * `ptr` is freed and a new expression in allocated
 */
void *rumba_expr_mul(void *lhs, void *rhs);

/**
 * Create a new substraction expression.
 * `ptr` is freed and a new expression in allocated
 */
void *rumba_expr_sub(void *lhs, void *rhs);

/**
 * Create a new neg expression.
 * `ptr` is freed and a new expression in allocated
 */
void *rumba_expr_neg(void *ptr);

/**
 * Clones an expression.
 */
void *rumba_expr_clone(const void *ptr);

#if defined(DEFINE_RUMBA_PARSE)
/**
 * Parses an expression from a string into res
 * If an error occurs returns 1
 */
uint8_t rumba_expr_parse(const char *ptr, void **res);
#endif

/**
 * Creates a new program
 */
void *rumba_make_program(void);

/**
 * Free a rumba program
 * # Safety
 * The caller promises that p is a valid pointer to a program
 */
void rumba_program_free(void *p);

/**
 * Simplifies a program
 * If an error occurs returns 1
 *
 * # Safety
 * The caller promises that p is a valid pointer to a program
 */
uint8_t rumba_program_simplify(void *p);

/**
 * Returns the number of instructions in a program
 *
 * # Safety
 * The caller promises that p is a valid pointer to a program
 */
uintptr_t rumba_program_size(void *p);

/**
 * Returns the i-th instructions in a program
 *
 * # Safety
 * The caller promises that p is a valid pointer to a program
 */
const void *rumba_program_get(void *p, uintptr_t i);

/**
 * Returns the id of an instruction
 *
 * # Safety
 * The caller promises that `insn` is a valid pointer to an instruction
 */
uintptr_t rumba_insn_id(const void *insn);

/**
 * Returns the type of an instruction
 *
 * # Safety
 * The caller promises that `insn` is a valid pointer to an instruction
 */
uint8_t rumba_insn_ty(const void *insn);

/**
 * Returns the kind of an instruction
 *
 * # Safety
 * The caller promises that `insn` is a valid pointer to an instruction
 */
enum InsnKind rumba_insn_kind(const void *insn);

/**
 * Returns the expression of an assign instruction
 *
 * # Safety
 * The caller promises that `insn` is a valid pointer to an instruction
 */
const void *rumba_insn_assign_get(const void *insn);

/**
 * Returns the number of args of an unkonwn instruction
 *
 * # Safety
 * The caller promises that `insn` is a valid pointer to an instruction
 */
uintptr_t rumba_insn_unknown_size(const void *insn);

/**
 * Returns the i-th arg of an unkonwn instruction
 *
 * # Safety
 * The caller promises that `insn` is a valid pointer to an instruction
 */
uintptr_t rumba_insn_unknown_get(const void *insn, uintptr_t i);

/**
 * Adds an unknown instruction to the program
 * If an error occurs returns 1
 *
 * # Safety
 * The caller promises that `p` is a valid pointer to a program
 * The caller promises that `args` is a valid pointer to an array of usize of size `args_len`
 */
uint8_t rumba_program_push_unknown(void *p,
                                   uint8_t ty,
                                   uintptr_t id,
                                   const uintptr_t *args,
                                   uintptr_t args_len);

/**
 * Adds an assign instruction
 * If an error occurs returns 1
 *
 * This takes ownership of the expression e
 *
 * # Safety
 * The caller promises that `p` is a valid pointer to a program
 * The caller promises that `e` is a valid pointer to an expression
 */
uint8_t rumba_program_push_assign(void *p, uint8_t ty, uintptr_t id, void *e);

/**
 * Retrieves a detailed explanation of the last error
 */
const char *get_err_str(void);

#endif  /* RUMBA_H */
